export const SKY_CONFIG = {
  density: 0.00115,
  minStars: 5200,
  maxStars: 18000,
  dprCap: 1.4,
  cameraPreset: "equatorial-night",
  observerLatitude: 0,
  lookAzimuth: 0,
  lookAltitude: 84,
  lookRoll: 0,
  fieldOfView: 90,
  motionScale: 5.8,
  timelapseEnabled: true,
  timelapseIntensity: 2.1,
  rotationSpeed: 0.00285,
  trailExposureSeconds: 42,
  trailTimeWarp: 14.2,
  backgroundParallax: 0.05,
  baseStarSize: 0.8,
  maxStarSize: 4.4,
  starSizeVariation: 2.55,
  sizeVariationEnabled: true,
  glowScale: 5,
  twinkleAmount: 0.36,
  twinkleSpeedMin: 0.9,
  twinkleSpeedMax: 3.6,
  horizonFadeStart: -0.08,
  horizonFadeEnd: 0.22,
  edgeFadeStart: 0.06,
  edgeFadeEnd: 0.94,
  driftSeed: 1.7,
  bandWeight: 0.88,
  bandFrequency: 2.15,
  bandAmplitude: 0.5,
  bandSpread: 0.28,
  bandPhase: 0.85,
  starSpread: 1,
  screenFill: 1.1,
  atmosphereEnabled: true,
  atmosphereStrength: 1.02,
  atmosphereGlow: 0.72,
  gravityEnabled: true,
  gravityStrength: 0.28,
  screenCoverageBoost: 0.26,
  edgeMagnification: 0.18,
  horizonMagnification: 0.24,
  meteorsEnabled: true,
  meteorRate: 1.4,
  meteorDurationMin: 0.68,
  meteorDurationMax: 1.18,
  meteorTrailLength: 0.19,
  meteorGlow: 0.95,
  meteorWidth: 1.85,
  maxActiveMeteors: 2,
};

export const TAU = Math.PI * 2;
export const DEG = Math.PI / 180;
