import { applyCameraPreset } from "./presets.js";

export const SCENE_PRESETS = {
  "aurora-night": {
    label: "Aurora Night",
    cameraPreset: "polar-arc",
    values: {
      density: 0.0008,
      minStars: 2200,
      maxStars: 8000,
      fieldOfView: 112,
      fisheyeEnabled: true,
      motionScale: 4.2,
      timelapseIntensity: 1.7,
      rotationSpeed: 0.0024,
      glowScale: 4.5,
      auroraEnabled: true,
      auroraIntensity: 0.95,
      auroraSpeed: 1.15,
      auroraHue: 135,
      auroraBands: 4,
      auroraHeight: 0.55,
      milkyWayEnabled: true,
      milkyWayIntensity: 0.35,
      nebulaEnabled: false,
      satellitesEnabled: true,
      satelliteRate: 2,
      meteorsEnabled: true,
      meteorRate: 1.2,
      cameraDriftEnabled: true,
      cameraDriftAmount: 2,
      depthParallaxEnabled: true,
      depthParallax: 0.3,
      trailsEnabled: false,
    },
  },
  "galactic-core": {
    label: "Galactic Core",
    cameraPreset: "equatorial-night",
    values: {
      density: 0.0012,
      minStars: 3400,
      maxStars: 12000,
      fieldOfView: 124,
      fisheyeEnabled: true,
      motionScale: 5.4,
      timelapseIntensity: 2.2,
      rotationSpeed: 0.003,
      bandWeight: 0.95,
      bandAmplitude: 0.55,
      bandSpread: 0.22,
      glowScale: 5.5,
      maxStarSize: 4.6,
      milkyWayEnabled: true,
      milkyWayIntensity: 1.2,
      nebulaEnabled: true,
      auroraEnabled: false,
      satellitesEnabled: true,
      satelliteRate: 1.2,
      meteorsEnabled: true,
      meteorRate: 1.8,
      cameraDriftEnabled: true,
      cameraDriftAmount: 2.8,
      depthParallaxEnabled: true,
      depthParallax: 0.45,
      trailsEnabled: false,
    },
  },
  "cinematic-zenith": {
    label: "Cinematic Zenith",
    cameraPreset: "zenith-drift",
    values: {
      density: 0.001,
      minStars: 2800,
      maxStars: 10000,
      fieldOfView: 130,
      fisheyeEnabled: true,
      motionScale: 6.4,
      timelapseIntensity: 2.6,
      rotationSpeed: 0.0035,
      trailTimeWarp: 14.5,
      baseStarSize: 0.92,
      maxStarSize: 4.8,
      starSizeVariation: 2.8,
      milkyWayEnabled: true,
      milkyWayIntensity: 0.5,
      nebulaEnabled: true,
      auroraEnabled: false,
      satellitesEnabled: true,
      satelliteRate: 1.4,
      meteorsEnabled: true,
      meteorRate: 2,
      cameraDriftEnabled: true,
      cameraDriftAmount: 3.2,
      depthParallaxEnabled: true,
      depthParallax: 0.5,
      trailsEnabled: false,
    },
  },
  "meteor-surge": {
    label: "Meteor Surge",
    cameraPreset: "equatorial-sweep",
    values: {
      density: 0.0013,
      minStars: 3200,
      maxStars: 12000,
      motionScale: 8.2,
      timelapseIntensity: 3.2,
      rotationSpeed: 0.0048,
      trailTimeWarp: 12,
      glowScale: 5.5,
      atmosphereStrength: 1.24,
      gravityStrength: 0.36,
      milkyWayEnabled: false,
      auroraEnabled: false,
      satellitesEnabled: false,
      meteorsEnabled: true,
      meteorRate: 9.5,
      meteorTrailLength: 0.42,
      meteorGlow: 1.55,
      meteorWidth: 2.65,
      maxActiveMeteors: 4,
      cameraDriftEnabled: true,
      cameraDriftAmount: 1.6,
      depthParallaxEnabled: true,
      depthParallax: 0.35,
      trailsEnabled: false,
    },
  },
  "benchmark-redline": {
    label: "Benchmark Redline",
    cameraPreset: "zenith-drift",
    values: {
      density: 0.0032,
      minStars: 16000,
      maxStars: 68000,
      dprCap: 1.75,
      motionScale: 11.5,
      timelapseIntensity: 4.6,
      rotationSpeed: 0.0068,
      trailTimeWarp: 28,
      backgroundParallax: 0.18,
      baseStarSize: 1.18,
      maxStarSize: 6.8,
      starSizeVariation: 3.6,
      bandAmplitude: 0.72,
      starSpread: 1.55,
      atmosphereStrength: 1.8,
      gravityStrength: 0.52,
      screenCoverageBoost: 1.2,
      edgeMagnification: 0.85,
      horizonMagnification: 1.1,
      milkyWayEnabled: true,
      milkyWayIntensity: 1.3,
      auroraEnabled: true,
      auroraIntensity: 1.1,
      auroraBands: 4,
      satellitesEnabled: true,
      satelliteRate: 4,
      meteorsEnabled: true,
      meteorRate: 16,
      meteorTrailLength: 0.58,
      meteorGlow: 2.1,
      meteorWidth: 3.4,
      maxActiveMeteors: 6,
      cameraDriftEnabled: true,
      cameraDriftAmount: 4,
      depthParallaxEnabled: true,
      depthParallax: 0.6,
      adaptiveQualityEnabled: false,
      trailsEnabled: false,
    },
  },
};

export const SCENE_PRESET_KEYS = Object.keys(SCENE_PRESETS);

export const applyScenePreset = (config, presetKey) => {
  const preset = SCENE_PRESETS[presetKey] ?? SCENE_PRESETS["cinematic-zenith"];
  applyCameraPreset(config, preset.cameraPreset);
  Object.assign(config, preset.values);
  return config;
};
